repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        args: [-w]
      - id: go-imports
        args: [-w, -local, github.com/ytakahashi/crewee]
      - id: golangci-lint
        args: [--config=backend/.golangci.yml]
        pass_filenames: false
        files: \.go$
        exclude: ^(migrations/|backend/internal/database/generated/)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$
        exclude: ^(backend/|infrastructure/cdk.out/)