run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/ytakahashi/crewee
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ytakahashi/crewee)
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use standard errors package"

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - gci

issues:
  exclude-dirs:
    - tmp
    - vendor
    - migrations
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
    - path: migrations/
      linters:
        - revive
        - gocritic
    - path: internal/database/generated/
      linters:
        - revive
        - gocritic
        - stylecheck
  max-issues-per-linter: 50
  max-same-issues: 3